package com.icure.cardinal.sdk.test

import com.icure.cardinal.sdk.CardinalSdk
import com.icure.cardinal.sdk.api.raw.RawMessageGatewayApi
import com.icure.cardinal.sdk.api.raw.impl.RawAnonymousAuthApiImpl
import com.icure.cardinal.sdk.auth.UsernamePassword
import com.icure.cardinal.sdk.options.AuthenticationMethod
import com.icure.cardinal.sdk.options.SdkOptions
import com.icure.cardinal.sdk.options.getAuthProvider
import com.icure.kryptom.crypto.defaultCryptoService
import com.icure.utils.InternalIcureApi

// These come from `TestConfig`, generated by the `generateTestConfig` gradle task: the value of each
// of them can be overridden through an environment variable (see `cardinal-sdk/build.gradle.kts`),
// so that the tests can run against an environment other than the local docker one.
val isLocalTestMode = TestConfig.TEST_MODE == "local"
val baseUrl = TestConfig.BASE_URL
val mockMessageGatewayUrl = TestConfig.MOCK_MESSAGE_GATEWAY_URL
val mockSpecId = TestConfig.MOCK_SPEC_ID
val testGroupName = TestConfig.TEST_GROUP_NAME
val testGroupId = TestConfig.TEST_GROUP_ID.takeIf { it.isNotBlank() } ?:
	(testGroupName + "-" + defaultCryptoService.strongRandom.randomUUID())
val testGroupAdmin = if (isLocalTestMode) "admin-{${uuid()}}@icure.com" else TestConfig.SUPERADMIN_USERNAME
val testGroupAdminPassword = if (isLocalTestMode) "admin-${uuid()}" else TestConfig.SUPERADMIN_PASSWORD

/**
 * Directory where the keys of the pre-configured test users are stored, so that they survive across
 * runs. Only used in a non-local environment, where the tests can't create their own data owners.
 */
val testKeyDirectory = TestConfig.KEY_DIRECTORY.takeIf { it.isNotBlank() }

/**
 * Credentials of the healthcare party users that already exist in a non-local test environment: there
 * the tests can't create their own data owners, so these are the only ones they can use.
 */
val preConfiguredHcpUsers: List<UserCredentials> = listOfNotNull(
	userCredentialsOrNull("TEST_USER_1", TestConfig.TEST_USER_1_ID, TestConfig.TEST_USER_1_PWD),
	userCredentialsOrNull("TEST_USER_2", TestConfig.TEST_USER_2_ID, TestConfig.TEST_USER_2_PWD),
)

/**
 * Login credentials of a user of the test environment.
 */
data class UserCredentials(
	val username: String,
	val password: String,
)

private fun userCredentialsOrNull(envVarPrefix: String, username: String, password: String): UserCredentials? =
	if (username.isBlank()) null else UserCredentials(
		username = username,
		password = password.takeIf { it.isNotBlank() }
			?: throw IllegalStateException("${envVarPrefix}_ID is set but ${envVarPrefix}_PWD is not"),
	)

@OptIn(InternalIcureApi::class)
internal suspend fun userAuth(username: String, password: String) =
	AuthenticationMethod.UsingCredentials(
		UsernamePassword(username, password),
	).getAuthProvider(
		RawAnonymousAuthApiImpl(baseUrl, DefaultRawApiConfig),
		defaultCryptoService,
		null,
		SdkOptions(),
		messageGatewayApi = RawMessageGatewayApi(CardinalSdk.sharedHttpClient, defaultCryptoService),
		krakenUrl = baseUrl
	)

@OptIn(InternalIcureApi::class)
internal suspend fun testGroupAdminAuth() = userAuth(testGroupAdmin, testGroupAdminPassword)

@OptIn(InternalIcureApi::class)
internal suspend fun superadminAuth() = userAuth(TestConfig.SUPERADMIN_USERNAME, TestConfig.SUPERADMIN_PASSWORD)
