import com.vanniktech.maven.publish.SonatypeHost
import tasks.InitializeTestEnvironment

plugins {
	ksp()
	kotest()
	kotlinMultiplatform()
	kotlinSerialization()
	androidLibrary()
	id("maven-publish")
	signing
	id("com.vanniktech.maven.publish") apply true
}

val repoUsername: String by project
val repoPassword: String by project
val mavenReleasesRepository: String by project

group = "com.icure"

val version = "3.0.0-PREVIEW-1"
project.version = version

val generateSdkVersion by tasks.registering {
	val outputDir = layout.buildDirectory.dir("generated/sdkVersion/kotlin")
	outputs.dir(outputDir)
	inputs.property("sdkVersion", version)
	doLast {
		val dir = outputDir.get().asFile.resolve("com/icure/cardinal/sdk/utils")
		dir.mkdirs()
		dir.resolve("SdkVersion.kt").writeText(
			"""
			|package com.icure.cardinal.sdk.utils
			|
			|internal const val SDK_VERSION: String = "$version"
			|""".trimMargin()
		)
	}
}

/**
 * Configuration of the test environment, with the defaults matching the local docker environment
 * started by `initializeTestEnvironment`. Each entry can be overridden through the environment
 * variable of the same name, so that the tests can run against a different environment on the CI.
 */
val testConfigProperties = mapOf(
	"TEST_MODE" to ("TEST_MODE" to "local"),
	"BASE_URL" to ("CARDINAL_TEST_BASE_URL" to "http://localhost:16044"),
	"MOCK_MESSAGE_GATEWAY_URL" to ("CARDINAL_TEST_MOCK_MESSAGE_GATEWAY_URL" to "http://127.0.0.1:8081/msggtw"),
	"MOCK_SPEC_ID" to ("CARDINAL_TEST_MOCK_SPEC_ID" to "ic"),
	"TEST_GROUP_NAME" to ("CARDINAL_TEST_GROUP_NAME" to "testgroup"),
	// Empty means "generate a new group id for this run", which only makes sense in a local environment.
	"TEST_GROUP_ID" to ("CARDINAL_TEST_GROUP_ID" to ""),
	"SUPERADMIN_USERNAME" to ("CARDINAL_TEST_SUPERADMIN_USERNAME" to "john"),
	"SUPERADMIN_PASSWORD" to ("CARDINAL_TEST_SUPERADMIN_PASSWORD" to "LetMeIn"), //pragma: allowlist secret
	"TEST_USER_1_ID" to ("TEST_USER_1_ID" to ""),
	"TEST_USER_1_PWD" to ("TEST_USER_1_PWD" to ""),
	"TEST_USER_2_ID" to ("TEST_USER_2_ID" to ""),
	"TEST_USER_2_PWD" to ("TEST_USER_2_PWD" to ""),
	"KEY_DIRECTORY" to ("KEY_DIRECTORY" to ""),
)

/**
 * The value of a test configuration property, read from its environment variable and falling back to
 * its default. It is a provider, so that gradle re-runs the tasks using it when the env var changes.
 */
fun testConfigProperty(constantName: String): Provider<String> =
	testConfigProperties.getValue(constantName).let { (envVar, default) ->
		providers.environmentVariable(envVar).orElse(default)
	}

/**
 * When this is `local` the tests run against the docker environment started by
 * `initializeTestEnvironment`; with any other value that task is skipped and the tests are expected
 * to run against an already existing environment (configured through the other env vars).
 */
val localTestMode = testConfigProperty("TEST_MODE").map { it == "local" }

val generateTestConfig by tasks.registering {
	group = "verification"

	val outputDir = layout.buildDirectory.dir("generated/testConfig/kotlin")
	outputs.dir(outputDir)
	val values = testConfigProperties.mapValues { (constantName, _) -> testConfigProperty(constantName) }
	values.forEach { (constantName, provider) -> inputs.property(constantName, provider) }
	doLast {
		val dir = outputDir.get().asFile.resolve("com/icure/cardinal/sdk/test")
		dir.mkdirs()
		val constants = values.entries.joinToString(separator = "\n") { (constantName, provider) ->
			val escaped = provider.get().replace("\\", "\\\\").replace("\"", "\\\"").replace("$", "\${'$'}")
			"""	const val $constantName: String = "$escaped""""
		}
		dir.resolve("TestConfig.kt").writeText(
			"""
			|// WARNING: This file is auto-generated by the `generateTestConfig` gradle task, do not edit it.
			|package com.icure.cardinal.sdk.test
			|
			|internal object TestConfig {
			|$constants
			|}
			|""".trimMargin()
		)
	}
}

kotlin {
	configureMultiplatform(this)

	sourceSets {
		commonMain {
			kotlin.srcDir(generateSdkVersion)
			dependencies {
				api(libs.ktorClientCore)
				implementation(libs.ktorContentNegotiation)
				implementation(libs.ktorSerializationJson)
				implementation(libs.ktorClientWebsocket)
				api(libs.kotlinSerialization)
				api(libs.kotlinDateTime)
				implementation(libs.kermit)
				api(libs.kryptom)
				api(libs.kerberus)
				implementation(libs.coroutinesCore)
				implementation(libs.okio)
				implementation(kotlin("reflect"))
			}
		}
		commonTest {
			kotlin.srcDir(generateTestConfig)
			dependencies {
				implementation(libs.kotestAssertions)
				implementation(libs.kotestEngine)
				implementation(libs.kotp)
				implementation(kotlin("test-common"))
				implementation(kotlin("test-annotations-common"))
			}
		}
		jvmMain {
			dependencies {
				implementation(libs.ktorClientEngineOkhttp)
				implementation(libs.bouncyCastle)
			}
		}
		jvmTest {
			dependencies {
				implementation(libs.kotestRunnerJunit)
				implementation(libs.ktorClientEngineCio) // Currently needed by test setup, remove later
				implementation(libs.mockk)
				implementation(libs.bundles.ktorServer)
			}
		}
		jsMain {
			dependencies {
				implementation(libs.ktorClientEngineJs)
			}
		}
		androidMain {
			dependencies {
				implementation(libs.ktorClientEngineOkhttp)
				compileOnly(libs.androidx.datastore)
			}
		}
		val androidHostTest by getting {
			dependencies {
				implementation(libs.kotestRunnerJunit)
			}
		}
		appleMain {
			dependencies {
				implementation(libs.ktorClientEngineDarwin)
			}
		}
		linuxMain {
			dependencies {
				implementation(libs.ktorClientEngineCurl)
			}
		}
		mingwMain {
			dependencies {
				implementation(libs.ktorClientEngineWinhttp)
			}
		}
	}
}

configureJvmTest()

dependencies {
	add("kspJvm", "com.icure:ksp-json-processor")
}

publishing {
	repositories {
		mavenLocal()
		maven {
			name = "Taktik"
			url = uri(mavenReleasesRepository)
			credentials {
				username = repoUsername
				password = repoPassword
			}
		}
	}
}

tasks.register<InitializeTestEnvironment>("initializeTestEnvironment") {
	// The local docker environment is only started when the tests actually run against it.
	onlyIf("TEST_MODE is \"local\"") { localTestMode.get() }
}

tasks.named("allTests") {
	dependsOn("initializeTestEnvironment")
}
tasks.named("iosSimulatorArm64Test") {
	dependsOn("initializeTestEnvironment")
}
tasks.named("iosX64Test") {
	dependsOn("initializeTestEnvironment")
}
tasks.named("jsBrowserTest") {
	dependsOn("initializeTestEnvironment")
}
tasks.named("jsNodeTest") {
	dependsOn("initializeTestEnvironment")
}
tasks.named("jsTest") {
	dependsOn("initializeTestEnvironment")
}
tasks.named("jvmTest") {
	dependsOn("initializeTestEnvironment")
}


//tasks.named("jsNodeDevelopmentRun") { dependsOn("jsProductionExecutableCompileSync") }
//tasks.named("jsNodeProductionRun") { dependsOn("jsProductionExecutableCompileSync") }

fun projectHasSignatureProperties() =
	project.hasProperty("signingInMemoryKeyId") && project.hasProperty("signingInMemoryKeyPassword") && project.hasProperty("signingInMemoryKey")
//
//if (projectHasSignatureProperties()) {
//	signing {
//		useInMemoryPgpKeys(
//			file(project.property("signing.secretKeyRingFile") as String).readText(),
//			project.property("signing.password") as String
//		)
//		sign(publishing.publications)
//	}
//}

mavenPublishing {
	val publishedArtifactId: String = (findProperty("artifactId") as String?)?.takeIf { it.isNotBlank() } ?: project.name
	coordinates(group as String, publishedArtifactId, project.version as String)

	pom {
		name.set("CardinalSDK")
		url.set("https://github.com/icure/icure-multiplatform-sdk")
		description.set("""
			Cardinal SDK is a multiplatform SDK for the iCure platform.
		""".trimIndent())

		licenses {
			license {
				name.set("MIT License")
				url.set("https://choosealicense.com/licenses/mit/")
				distribution.set("https://choosealicense.com/licenses/mit/")
			}
		}
		developers {
			developer {
				id.set("icure")
				name.set("iCure")
				url.set("https://github.com/iCure/")
			}
		}
		scm {
			url.set("https://github.com/icure/icure-multiplatform-sdk")
			connection.set("scm:git:git://github.com/icure/icure-multiplatform-sdk.git")
			developerConnection.set("scm:git:ssh://git@github.com:icure/icure-multiplatform-sdk.git")
		}
	}

	publishToMavenCentral(SonatypeHost.CENTRAL_PORTAL, automaticRelease = true)

	if (projectHasSignatureProperties()) {
		signAllPublications()
	}
}

// Configure all publishing tasks
if (!projectHasSignatureProperties()) {
	tasks.withType<PublishToMavenRepository> {
		doFirst {
			throw IllegalStateException("Cannot publish to Maven Central without signing properties")
		}
	}
}
