approvedGitRepositories:
  - "**"

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

npmPreapprovedPackages:
  - "@icure/cardinal-sdk"

npmRegistryServer: "https://registry.npmjs.org"

npmScopes:
  icure:
    npmRegistryServer: "https://registry.npmjs.org"
