[versions]
kotlin = "1.9.22"
ktor = "2.3.7"
coroutines = "1.7.3"
kotlinSerialization = "1.6.1"
kotest = "5.8.0"
androidLibrary = "8.2.0"
bouncyCastle = "1.70"
androidConscrypt = "2.5.2"

[libraries]
# Ktor
ktorClientCore = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktorClientEngineAndroid = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktorClientEngineIos = { group = "io.ktor", name = "ktor-client-darwin", version.ref = "ktor" }
ktorClientEngineJs = { group = "io.ktor", name = "ktor-client-js", version.ref = "ktor" }
ktorClientEngineJvm = { group = "io.ktor", name = "ktor-client-jetty", version.ref = "ktor" }
ktorContentNegotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktorSerializationJson = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
# Kotlinx
coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinSerialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinSerialization" }
# Kotest
kotestAssertions = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
kotestEngine = { group = "io.kotest", name = "kotest-framework-engine", version.ref = "kotest" }
kotestDatatest = { group = "io.kotest", name = "kotest-framework-datatest", version.ref = "kotest" }
kotestRunnerJunit = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest" }
# Cryptography providers
bouncyCastle = { group = "org.bouncycastle", name = "bcprov-jdk15on", version.ref = "bouncyCastle" }
androidConscrypt = { group = "org.conscrypt", name = "conscrypt-android", version.ref = "androidConscrypt" }

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotestMultiplatform = { id = "io.kotest.multiplatform", version.ref = "kotest" }
androidLibrary = { id = "com.android.library", version.ref = "androidLibrary" }
