package com.icure.cardinal.sdk.crypto.pairing

import com.icure.cardinal.sdk.utils.DEFAULT_ENABLED
import com.icure.kryptom.crypto.defaultCryptoService
import com.icure.kryptom.utils.hexToByteArray
import com.icure.kryptom.utils.toHexString
import io.kotest.assertions.throwables.shouldThrow
import io.kotest.assertions.withClue
import io.kotest.core.spec.style.StringSpec
import io.kotest.matchers.shouldBe
import io.kotest.matchers.shouldNotBe
import io.kotest.matchers.types.shouldBeInstanceOf
import io.kotest.matchers.types.shouldNotBeInstanceOf

/**
 * version, x, expected code, checksum. Generated by secp160r1-pairing's `tools/secp160r1-ref/secp160r1_ref.py` (an
 * independent Python implementation of the format); regenerate there, never edit by hand.
 */
private val codeVectors: List<List<String>> = listOf(
	listOf("1", "4a96b5688ef573284664698968c38bb913cbfc82", "19AB-BAT4-EYNS-JGHK-4D64-PHGW-BQ49-WQZ4-2NW6", "22406"),
	listOf("1", "02f997f33c5ed04c55d3edf8675d3e92e8f46686", "10BW-SFWS-WBV8-4RNE-KXQW-6EQ9-YJBM-F8SM-68SH", "9009"),
	listOf("1", "7b76ff541ef363f2df13de1650bd48daa958bc59", "1FDV-FYN0-YYDH-Z5QR-KVRB-51FA-8VAM-NHF2-SK78", "19688"),
	listOf("1", "f38f72a7a105f7cb4fa69bcba10548ad96849970", "1YE7-Q59X-10QV-WPKX-6KF5-T21A-8NPB-896B-G8VC", "9068"),
	listOf("1", "e0339b3160311f83273cc1c108d126347876909e", "1W0S-SPCB-064F-R69S-WR70-GHM9-66HW-7D44-YK6W", "19676"),
)

/** An x-coordinate that is not on the curve (x = 3, see the `decompress` vectors in kryptom). */
private const val OFF_CURVE_X = "0000000000000000000000000000000000000003"

class PairingCodeTest : StringSpec({
	val digest = defaultCryptoService.digest
	suspend fun parse(typed: String) = PairingCode.decode(digest, typed)
	suspend fun parsedKey(typed: String): String =
		parse(typed).shouldBeInstanceOf<PairingCodeParseResult.Parsed>().publicKeyX.toHexString()
	fun flat(code: String) = code.replace("-", "")

	"encoding matches the reference vectors symbol for symbol".config(enabled = DEFAULT_ENABLED) {
		codeVectors.forEach { (version, x, code, checksum) ->
			PairingCode.encode(digest, hexToByteArray(x), version.toInt()) shouldBe code
			PairingCode.checksum(digest, version.toInt(), hexToByteArray(x)) shouldBe checksum.toInt()
		}
	}

	"decoding the displayed form recovers the version and the key".config(enabled = DEFAULT_ENABLED) {
		codeVectors.forEach { (version, x, code, _) ->
			val parsed = parse(code).shouldBeInstanceOf<PairingCodeParseResult.Parsed>()
			parsed.version shouldBe version.toInt()
			parsed.publicKeyX.toHexString() shouldBe x
		}
	}

	"every way a person plausibly types the code is accepted".config(enabled = DEFAULT_ENABLED) {
		codeVectors.forEach { (_, x, code, _) ->
			val f = flat(code)
			listOf(
				f,
				code.lowercase(),
				f.lowercase(),
				code.replace('-', ' '),
				"  $code \n",
				"\t$f\t",
				f.chunked(2).joinToString("-"),
				f.chunked(4).joinToString("_"),
				f.chunked(6).joinToString(" - "),
				code.replace("-", "\u2013"),
			).forEach { variant -> withClue(variant) { parsedKey(variant) shouldBe x } }
		}
	}

	"ambiguous glyphs fold onto the digit the person meant".config(enabled = DEFAULT_ENABLED) {
		val withBoth = codeVectors.filter { (_, _, code, _) -> '0' in code && '1' in code }
		withBoth.size shouldNotBe 0
		withBoth.forEach { (_, x, code, _) ->
			parsedKey(code.replace('0', 'O').replace('1', 'l')) shouldBe x
			parsedKey(code.replace('0', 'o').replace('1', 'I')) shouldBe x
			parsedKey(code.replace('1', 'i').replace('0', 'O').lowercase()) shouldBe x
		}
	}

	"U is rejected as malformed, never folded".config(enabled = DEFAULT_ENABLED) {
		val f = flat(codeVectors[0][2])
		parse("U" + f.drop(1)).shouldBeInstanceOf<PairingCodeParseResult.Malformed>()
		parse(f.dropLast(1) + "u").shouldBeInstanceOf<PairingCodeParseResult.Malformed>()
		parse(f.substring(0, 10) + "U" + f.substring(11)).shouldBeInstanceOf<PairingCodeParseResult.Malformed>()
	}

	"wrong lengths are malformed".config(enabled = DEFAULT_ENABLED) {
		val f = flat(codeVectors[0][2])
		listOf(f.dropLast(1), f + "A", "", "-- -", f + f, f.take(4)).forEach {
			withClue("'$it'") { parse(it).shouldBeInstanceOf<PairingCodeParseResult.Malformed>() }
		}
	}

	"characters outside the alphabet are malformed".config(enabled = DEFAULT_ENABLED) {
		val f = flat(codeVectors[0][2])
		listOf('!', '*', '.', 'é', '/', '+', '=').forEach { c ->
			withClue(c) { parse(f.substring(0, 7) + c + f.substring(8)).shouldBeInstanceOf<PairingCodeParseResult.Malformed>() }
		}
	}

	"an unknown version is reported as such, before and distinctly from the checksum".config(enabled = DEFAULT_ENABLED) {
		val f = flat(codeVectors[0][2])
		parse("2" + f.drop(1)) shouldBe PairingCodeParseResult.UnknownVersion(2)
		parse("0" + f.drop(1)) shouldBe PairingCodeParseResult.UnknownVersion(0)
		parse("Z" + f.drop(1)) shouldBe PairingCodeParseResult.UnknownVersion(31)
	}

	"no single-symbol substitution is ever parsed as another key".config(enabled = DEFAULT_ENABLED) {
		// Exhaustive: 36 positions x 31 alternatives for each vector. With a 15-bit checksum a substitution in the
		// key symbols slips through with probability 2^-15; the Python reference confirmed that none of these
		// 5580 mutations does, so the expectation below is exact and deterministic, not a rate.
		var checksumFailed = 0
		var versionRejected = 0
		var total = 0
		codeVectors.forEach { (_, x, code, _) ->
			val f = flat(code)
			for (i in f.indices) for (c in CrockfordBase32.ALPHABET) {
				if (c == f[i]) continue
				total++
				when (val r = parse(f.substring(0, i) + c + f.substring(i + 1))) {
					is PairingCodeParseResult.Parsed -> withClue("position $i symbol $c") { r.publicKeyX.toHexString() shouldBe x }
					PairingCodeParseResult.ChecksumFailed -> checksumFailed++
					is PairingCodeParseResult.UnknownVersion -> versionRejected++
					is PairingCodeParseResult.Malformed -> error("a substitution inside the alphabet must never be malformed")
				}
			}
		}
		total shouldBe codeVectors.size * PairingCode.SYMBOL_COUNT * 31
		versionRejected shouldBe codeVectors.size * 31
		checksumFailed shouldBe total - versionRejected
		(checksumFailed.toDouble() / (total - versionRejected)) shouldBe 1.0
	}

	"no adjacent transposition is silently accepted".config(enabled = DEFAULT_ENABLED) {
		var tested = 0
		codeVectors.forEach { (_, _, code, _) ->
			val f = flat(code)
			for (i in 0 until f.length - 1) {
				if (f[i] == f[i + 1]) continue
				tested++
				val swapped = f.substring(0, i) + f[i + 1] + f[i] + f.substring(i + 2)
				withClue("swap at $i") { parse(swapped).shouldNotBeInstanceOf<PairingCodeParseResult.Parsed>() }
			}
		}
		tested shouldBe 170
	}

	"the checksum is a typo detector, not a signature: a forged off-curve code parses".config(enabled = DEFAULT_ENABLED) {
		// This is what makes point validation in the protocol layer mandatory: see PairingProtocolTest.
		val forged = PairingCode.encode(digest, hexToByteArray(OFF_CURVE_X))
		parsedKey(forged) shouldBe OFF_CURVE_X
	}

	"the checksum is bound to the version".config(enabled = DEFAULT_ENABLED) {
		codeVectors.count { (_, x, _, _) ->
			PairingCode.checksum(digest, 1, hexToByteArray(x)) != PairingCode.checksum(digest, 2, hexToByteArray(x))
		} shouldNotBe 0
	}

	"length-prefixed concatenation separates what plain concatenation merges".config(enabled = DEFAULT_ENABLED) {
		val ab = "ab".encodeToByteArray()
		val c = "c".encodeToByteArray()
		val a = "a".encodeToByteArray()
		val bc = "bc".encodeToByteArray()
		(ab + c).toHexString() shouldBe (a + bc).toHexString() // the ambiguity plain concatenation has
		lengthPrefixed(ab, c).toHexString() shouldNotBe lengthPrefixed(a, bc).toHexString()
		digest.sha256(lengthPrefixed(ab, c)).toHexString() shouldNotBe digest.sha256(lengthPrefixed(a, bc)).toHexString()
		lengthPrefixed(byteArrayOf(1, 2), ByteArray(0)).toHexString() shouldBe "0000000201020000" + "0000"
		lengthPrefixed().size shouldBe 0
	}

	"arbitrary 20-byte keys round-trip through encode and decode".config(enabled = DEFAULT_ENABLED) {
		repeat(20) {
			val x = defaultCryptoService.strongRandom.randomBytes(20)
			parsedKey(PairingCode.encode(digest, x)) shouldBe x.toHexString()
		}
		PairingCode.encode(digest, ByteArray(20)).let { parsedKey(it) shouldBe "0".repeat(40) }
		PairingCode.encode(digest, ByteArray(20) { 0xFF.toByte() }).let { parsedKey(it) shouldBe "f".repeat(40) }
	}

	"encode rejects keys of the wrong size and versions that do not fit in a symbol".config(enabled = DEFAULT_ENABLED) {
		shouldThrow<IllegalArgumentException> { PairingCode.encode(digest, ByteArray(19)) }
		shouldThrow<IllegalArgumentException> { PairingCode.encode(digest, ByteArray(21)) }
		shouldThrow<IllegalArgumentException> { PairingCode.encode(digest, ByteArray(20), 32) }
	}
})
