import java.io.FileWriter

plugins {
	kotlinMultiplatform()
}

val version: String? by project
project.version = version ?: "0.0.0-snapshot"

val moduleName = "cardinal-sdk-ts"

kotlin {
	configureKotlinJs(this, moduleName)

	sourceSets {
		val jsMain by getting {
			dependencies {
				implementation(project(":cardinal-sdk"))
				implementation(libs.coroutinesCore)
				implementation(libs.ktorClientCore)
			}
			languageSettings.optIn("kotlin.js.ExperimentalJsExport")
			languageSettings.optIn("kotlinx.coroutines.DelicateCoroutinesApi")
			languageSettings.optIn("kotlin.time.ExperimentalTime")
		}
	}
}

// TODO should become task type
tasks.register("clearAutoGenerated") {
	doLast {
		projectDir.resolve("src").walkBottomUp().forEach {
			if (it.isFile && it.readLines().firstOrNull()?.startsWith("// auto-generated file") == true) {
				it.delete()
			} else if (it.isDirectory && it.listFiles()!!.isEmpty()) {
				it.delete()
			}
		}
	}
}

fun File.mergeInto(other: File) {
	check(isDirectory && other.isDirectory) { "Can only merge a directory into another directory - ${this.absolutePath} -> ${other.absolutePath}" }
	val otherFiles = other.listFiles()!!.groupBy { it.name }.mapValues {
		check (it.value.size == 1) { "Duplicate file names" }
		it.value.first()
	}
	listFiles()!!.forEach { curr ->
		if (otherFiles.containsKey(curr.name)) {
			val otherCurr = otherFiles.getValue(curr.name)
			check (curr.isDirectory == otherCurr.isDirectory) {
				"Generated isDirectory != existing isDirectory - ${curr.absolutePath} -> ${otherCurr.absolutePath}"
			}
			if (curr.isDirectory) {
				curr.mergeInto(otherCurr)
			} else {
				curr.copyTo(otherCurr, overwrite = true)
			}
		} else {
			curr.copyRecursively(other.resolve(curr.name))
		}
	}
}

// TODO should become task type
tasks.register("updateAutoGenerated") {
	doLast {
		rootDir.resolve("cardinal-sdk/build/generated/ksp/jvm/jvmMain/resources/kt").mergeInto(
			projectDir.resolve("src/jsMain/kotlin")
		)
		rootDir.resolve("cardinal-sdk/build/generated/ksp/jvm/jvmMain/resources/ts").mergeInto(
			projectDir.resolve("src/jsMain/typescript")
		)
	}
}

// region jsDistribution

val ktJsCompiledPackage = projectDir.resolve("build/dist/js/productionLibrary")
val tsSources = projectDir.resolve("src/jsMain/typescript")
val mergedTsProject = projectDir.resolve("build/tsSourcesProject")
val tsCompiledSources = projectDir.resolve("build/tsCompiledSources")
val tsPackage = projectDir.resolve("build/tsPackage")

interface Import {
	val entry: String
	data class Default(
		val importedName: String,
		val from: String
	) : Import {
		override val entry: String
			get() = "import $importedName from '$from'"

	}
	data class Module(
		val importedName: String,
		val from: String
	) : Import  {
		override val entry: String
			get() = "import * as $importedName from '$from'"
	}
	data class Selective(
		val items: Set<String>,
		val from: String
	) : Import  {
		override val entry: String
			get() = "import { ${items.joinToString(", ")} } from '$from'"
	}
}
data class Replacement(
	val of: String,
	val with: String
)
interface Export {
	val entry: String
	data class Module(
		val from: String
	) : Export {
		override val entry: String
			get() = "export * from '$from'"
	}
	data class Selective(
		val items: List<String>,
		val from: String
	) : Export {
		override val entry: String
			get() = "export { ${items.joinToString(",")} } from '$from'"
	}
}
fun copyJsPatching(
	from: File,
	into: File,
	importing: List<Import> = emptyList(),
	replacing: List<Replacement> = emptyList(),
	exporting: List<Export> = emptyList()
) {
	FileWriter(into).use { fw ->
		importing.forEach {
			fw.write(it.entry + "\n")
		}
		replacing.fold(from.readText()) { acc, replacement ->
			val fixed = acc.replace(replacement.of, replacement.with)
			check (fixed != acc) { "Couldn't apply replacement $replacement" }
			fixed
		}.also {
			fw.write(it)
			if (!it.endsWith('\n')) fw.write("\n")
		}
		exporting.forEach {
			fw.write(it.entry + "\n")
		}
	}
}

fun getTypescriptSourcePackages() = tsSources.listFiles()!!.filter { it.isDirectory && it.name != "internal" }

fun File.tsPackageAsImport() =
	Import.Module(name, "./${name}.mjs")

fun File.tsPackageAsExport() = Export.Module("./${name}.mjs")

val prepareTypescriptSourceCompilation = tasks.register("prepareTypescriptSourceCompilation") {
	dependsOn("jsNodeProductionLibraryDistribution")
	inputs.dir(tsSources)
	outputs.dir(mergedTsProject)
	doLast {
		delete(mergedTsProject)
		copy {
			from(tsSources)
			into(mergedTsProject)
		}
		copyJsPatching(
			from = ktJsCompiledPackage.resolve("$moduleName.d.mts"),
			into = mergedTsProject.resolve("$moduleName.d.mts"),
			importing = getTypescriptSourcePackages().map { it.tsPackageAsImport() },
			exporting = getTypescriptSourcePackages().map { it.tsPackageAsExport() },
			replacing = listOf(
				Replacement(
					of = "cryptoService?: Nullable<PartialXCryptoService>",
					with = "cryptoService?: Nullable<crypto.PartialXCryptoService>"
				),
			)
		)
		// Generate index files for each package
		val tsPackages = tsSources.listFiles()!!.filter { it.isDirectory && it.name != "internal" }
		tsPackages.forEach { tsPackage ->
			FileWriter(mergedTsProject.resolve("${tsPackage.name}.mts")).use { fw ->
				tsPackage.walkTopDown().filter {
					!it.isDirectory && it.name.endsWith(".mts")
				}.forEach { currFile ->
					val currFilePath = currFile.relativeTo(tsSources).path.removeSuffix(".mts")
					fw.write("export * from './$currFilePath.mjs'\n")
				}
			}
		}
	}
}

val tscPath = providers.exec {
	commandLine("bash", "-c", "which tsc")
}.standardOutput.asText.map { it.trim() }

val compileTypescriptSources = tasks.register("compileTypescriptSources") {
	// Note: requires tsc in path
	// Typescript configuration from tsconfig
	dependsOn(prepareTypescriptSourceCompilation)
	inputs.dir(projectDir.resolve(mergedTsProject))
	inputs.file(projectDir.resolve("tsconfig.json"))
	outputs.dir(tsCompiledSources)
	doLast {
		tsCompiledSources.deleteRecursively()
		val tsc = tscPath.get()
		println(tsc)
		val exitCode = ProcessBuilder(tsc, "--project", projectDir.path)
			.inheritIO()
			.start()
			.waitFor()
		check(exitCode == 0) { "tsc exited with code $exitCode" }
	}
}

tasks.register("prepareDistributionPackage") {
	group = "publishing"
	dependsOn(compileTypescriptSources)
	val filesNeedingPatch = setOf(
		"$moduleName.mjs",
		"$moduleName.d.mts",
		"package.json",
		"kotlinx-coroutines-core.mjs"
	)
	doLast {
		copy {
			from(tsCompiledSources)
			into(tsPackage)
		}
		copy {
			from(ktJsCompiledPackage)
			into(tsPackage)
			exclude {
				it.name in filesNeedingPatch
			}
		}
		val tsSourcePackages = getTypescriptSourcePackages()
		val tsSourcePackagesImport = tsSourcePackages.map { it.tsPackageAsImport() }
		val tsSourcePackageExports = tsSourcePackages.map { it.tsPackageAsExport() }
		copyJsPatching(
			from = ktJsCompiledPackage.resolve("$moduleName.d.mts"),
			into = tsPackage.resolve("$moduleName.d.mts"),
			importing = tsSourcePackagesImport,
			exporting = tsSourcePackageExports,
			replacing = listOf(
				Replacement(
					of = "cryptoService?: Nullable<PartialXCryptoService>",
					with = "cryptoService?: Nullable<crypto.PartialXCryptoService>"
				)
			)
		)
		copyJsPatching(
			from = ktJsCompiledPackage.resolve("kotlinx-coroutines-core.mjs"),
			into = tsPackage.resolve("kotlinx-coroutines-core.mjs"),
			replacing = listOf(
				Replacement(
					of = "if (isJsdom()) {",
					with =
						"if (schedule_queue_patch == undefined) {\n" +
						"  if (typeof process !== 'undefined' && process !== null && typeof process.nextTick !== 'undefined') {\n" +
						"    schedule_queue_patch = process.nextTick;\n" +
						"  } else if (typeof setImmediate !== 'undefined') {\n" +
						"    schedule_queue_patch = setImmediate;\n" +
						"  } else {\n" +
						"    schedule_queue_patch = () => { throw new Error('Not used in this environment') };\n" +
						"  }\n" +
						"}\n" +
						"if (isJsdom() || (typeof navigator !== 'undefined' && navigator !== null && navigator.product === \"ReactNative\")) {\n",
				),
				Replacement(
					of = "function NodeDispatcher() {",
					with = "var schedule_queue_patch;\n" +
						"function NodeDispatcher() {"
				),
				Replacement(
					of = " = function () {\n" +
						"  process.nextTick(",
					with = " = function () {\n" +
						"  schedule_queue_patch("
				),
			)
		)
		copyJsPatching(
			from = ktJsCompiledPackage.resolve("$moduleName.mjs"),
			into = tsPackage.resolve("$moduleName.mjs"),
			importing = tsSourcePackagesImport,
			exporting = tsSourcePackageExports + Export.Selective(
				// Add exports from multiplatform module (not ts wrapper)
				listOf("RevisionConflictException"),
				"./cardinal-sdk.mjs"
			)
		)
		copyJsPatching(
			from = ktJsCompiledPackage.resolve("package.json"),
			into = tsPackage.resolve("package.json"),
			replacing = listOf(
				Replacement("\"name\": \"$moduleName\"", with = "\"name\": \"@icure/cardinal-sdk\""),
				Replacement("\"version\": \"0.0.0-unspecified\"", with = "\"version\": \"${project(":cardinal-sdk").version}\""),
				Replacement("\n}", with = ",\n  \"browser\": { \"ws\": false }\n}")
			)
		)
	}
}

// endregion

// region codegenMetaDistribution

// The `@icure/cardinal-sdk-generator-meta` npm package: the charix IR of this sdk, plus the metadata the customised sdk
// generator (icure/sdk-codegen) needs in order to target this version of cardinal. It is a data-only package - nothing
// in it is meant to be imported at runtime.
//
// Deliberately *not* wired into `prepareDistributionPackage`: the ts wrapper sources are updated from codegen by hand
// (`updateAutoGenerated`), and this package does not need that step at all. It only needs ksp to have produced the IR,
// so it depends directly on `:cardinal-sdk:kspKotlinJvm`.

val codegenMetaPackageName = "@icure/cardinal-sdk-generator-meta"

// `kt` and `ts` siblings of this directory are generated sdk sources rather than IR, and the generator does not read
// them - only `com` is shipped.
val irSources = rootDir.resolve("cardinal-sdk/build/generated/ksp/jvm/jvmMain/resources/com")

// Hand-tracked inputs that are not derived from the sdk sources. See its README.
val customisedSdkResources = rootDir.resolve("customised-sdk-resources")
val generatorCompatibilityFileName = "generator-compatibility.json"

val codegenMetaPackage = projectDir.resolve("build/codegenMetaPackage")

/**
 * Removes insignificant whitespace from a json document, without parsing it.
 *
 * Deliberately not a parse-and-re-serialise: round-tripping through a json library can renormalise number
 * formatting (`1.0` vs `1`, large integers into scientific notation) and is at the mercy of the library's map
 * ordering. Dropping bytes that carry no meaning cannot change the parsed value, and is stable run to run.
 */
fun minifyJson(json: String): String = buildString(json.length) {
	var inString = false
	var escaped = false
	json.forEach { c ->
		when {
			escaped -> { append(c); escaped = false }
			inString && c == '\\' -> { append(c); escaped = true }
			c == '"' -> { append(c); inString = !inString }
			inString -> append(c)
			c == ' ' || c == '\t' || c == '\n' || c == '\r' -> Unit
			else -> append(c)
		}
	}
}

tasks.register("prepareCodegenMetaPackage") {
	group = "publishing"
	description = "Lays out the $codegenMetaPackageName npm package under build/codegenMetaPackage."

	dependsOn(":cardinal-sdk:kspKotlinJvm")

	val sdkVersion = project(":cardinal-sdk").version.toString()

	inputs.dir(irSources)
	inputs.dir(customisedSdkResources)
	inputs.property("sdkVersion", sdkVersion)
	inputs.property("packageName", codegenMetaPackageName)
	outputs.dir(codegenMetaPackage)

	doLast {
		delete(codegenMetaPackage)

		// The generator resolves declarations by canonical name against the root it is given, so the package tree has
		// to be preserved: `ir/com/icure/cardinal/sdk/...`, with `ir` as the root handed to the generator.
		//
		// Shipped minified: ksp pretty-prints its output, and the indentation is more than half of it - 52.8 MB of
		// loose files becomes 22.8 MB, in every consumer's node_modules. The pretty-printed originals stay in the
		// ksp output directory for anyone who needs to read them.
		val irTarget = codegenMetaPackage.resolve("ir/com")
		irSources.walkTopDown().filter { it.isFile }.forEach { source ->
			val target = irTarget.resolve(source.relativeTo(irSources).path)
			target.parentFile.mkdirs()
			if (source.extension == "json") {
				target.writeText(minifyJson(source.readText()))
			} else {
				source.copyTo(target, overwrite = true)
			}
		}

		// Everything else in customised-sdk-resources is shipped as is; the compatibility file is not, it gets merged
		// with the sdk version below.
		val excludedResources = setOf(generatorCompatibilityFileName, "README.md")
		copy {
			from(customisedSdkResources)
			into(codegenMetaPackage)
			exclude { it.name in excludedResources }
		}
		// Derived rather than hardcoded, so adding a file to customised-sdk-resources is enough to publish it.
		val shippedResources = (customisedSdkResources.listFiles() ?: emptyArray())
			.filter { it.isFile && it.name !in excludedResources }
			.map { it.name }
			.sorted()

		val compatibilityFile = customisedSdkResources.resolve(generatorCompatibilityFileName)
		check(compatibilityFile.isFile) { "Missing $compatibilityFile" }
		val compatibility = groovy.json.JsonSlurper().parse(compatibilityFile) as Map<*, *>
		listOf("minimumRequiredGeneratorVersion", "minimumRecommendedGeneratorVersion").forEach {
			check(compatibility[it] is String) { "Missing or non-string `$it` in $compatibilityFile" }
		}

		// The sdk version is taken from the gradle module rather than tracked by hand, so the two cannot drift.
		codegenMetaPackage.resolve("codegen-meta.json").writeText(
			groovy.json.JsonOutput.prettyPrint(
				groovy.json.JsonOutput.toJson(
					linkedMapOf<String, Any?>("cardinalSdkVersion" to sdkVersion) + compatibility
				)
			) + "\n"
		)

		codegenMetaPackage.resolve("package.json").writeText(
			groovy.json.JsonOutput.prettyPrint(
				groovy.json.JsonOutput.toJson(
					linkedMapOf(
						"name" to codegenMetaPackageName,
						"version" to sdkVersion,
						"description" to "Charix IR and generation metadata for @icure/cardinal-sdk, consumed by the " +
							"customised cardinal sdk generator. Not intended to be imported.",
						"license" to "MIT",
						// Published in lockstep with the sdk: an exact peer dependency makes the package manager
						// reject a mismatched pair at install time, rather than the generator discovering it later.
						"peerDependencies" to mapOf("@icure/cardinal-sdk" to sdkVersion),
						// Only `package.json` is resolvable; the data files are read from disk by the generator after
						// resolving it, and stay unreachable to `import`.
						"exports" to mapOf("./package.json" to "./package.json"),
						"files" to listOf("ir", "codegen-meta.json") + shippedResources,
					)
				)
			) + "\n"
		)
	}
}

// endregion
