import kotlin.io.writeText

plugins {
	kotlinMultiplatform()
	kotlinSerialization()
}

val version: String? by project
project.version = version ?: "0.0.0-snapshot"

kotlin {
	val sharedLibBaseName = "cardinal-sdk-native-pylib"
	configureKotlinLinux(this).forEach {
		it.binaries {
			sharedLib {
				baseName = sharedLibBaseName
			}
		}
	}
	macosArm64 {
		binaries {
			sharedLib {
				baseName = sharedLibBaseName
			}
		}
	}
	mingwX64 {
		binaries {
			sharedLib {
				baseName = sharedLibBaseName
			}
		}
	}

	sourceSets {
		commonMain {
			dependencies {
				implementation(project(":cardinal-sdk"))
				implementation(libs.coroutinesCore)
			}
		}
		all {
			languageSettings.optIn("kotlin.time.ExperimentalTime")
		}
	}
}

// TODO should become task type
tasks.register("clearAutoGenerated") {
	doLast {
		projectDir.resolve("src").walkBottomUp().forEach {
			if (
				it.isFile && (
					it.readLines().firstOrNull()?.startsWith("// auto-generated file") == true ||
					it.readLines().firstOrNull()?.startsWith("# auto-generated file") == true
				)
			) {
				it.delete()
			} else if (it.isDirectory && it.listFiles()!!.isEmpty()) {
				it.delete()
			}
		}
	}
}

fun File.mergeInto(other: File) {
	check(isDirectory && other.isDirectory) { "Can only merge a directory into another directory - ${this.absolutePath} -> ${other.absolutePath}" }
	val otherFiles = other.listFiles()!!.groupBy { it.name }.mapValues {
		check (it.value.size == 1) { "Duplicate file names" }
		it.value.first()
	}
	listFiles()!!.forEach { curr ->
		if (otherFiles.containsKey(curr.name)) {
			val otherCurr = otherFiles.getValue(curr.name)
			check (curr.isDirectory == otherCurr.isDirectory) {
				"Generated isDirectory != existing isDirectory - ${curr.absolutePath} -> ${otherCurr.absolutePath}"
			}
			if (curr.isDirectory) {
				curr.mergeInto(otherCurr)
			} else {
				curr.copyTo(otherCurr, overwrite = true)
			}
		} else {
			curr.copyRecursively(other.resolve(curr.name))
		}
	}
}

fun rsync(source: File, dst: File) {
	val sourcePath = if (source.isDirectory) "${source.absolutePath}/" else source.absolutePath
	val exitCode = ProcessBuilder("rsync", "-a", sourcePath, dst.absolutePath)
		.inheritIO()
		.start()
		.waitFor()
	check(exitCode == 0) { "rsync exited with code $exitCode" }
}

fun remove(source: File) {
	val exitCode = ProcessBuilder("rm", "-rf", source.absolutePath)
		.inheritIO()
		.start()
		.waitFor()
	check(exitCode == 0) { "rm exited with code $exitCode" }
}

val pythonPath = (providers.gradleProperty("pythonExecutable").orNull
	?: providers.environmentVariable("PYTHON_EXECUTABLE").orNull)
	?.let { providers.provider { it } }
	?: providers.exec {
		commandLine("bash", "-c", "command -v python3.12 || command -v python3")
	}.standardOutput.asText.map {
		it.trim().ifEmpty { error("No python3.12 found on PATH") }
	}

fun removeDistDir() {
	val distDir = projectDir.resolve("src/commonMain/resources/dist")
	if (distDir.exists()) {
		remove(distDir)
	}
}

fun prepareDistributionArchive(
	nativeLibBaseFolder: String,
	nativeLibFolder: String,
	nativeLibFileName: String,
	platformNameBuildOption: String
) {
	val srcDir = projectDir.resolve("src/commonMain/resources/src")
	if (srcDir.exists()) {
		remove(srcDir)
	}

	val buildDir = projectDir.resolve("src/commonMain/resources/build")
	if (buildDir.exists()) {
		remove(buildDir)
	}

	val venvDir = projectDir.resolve("src/commonMain/resources/venv")
	if (venvDir.exists()) {
		remove(venvDir)
	}

	projectDir.resolve("src/commonMain/resources/src").mkdirs()
	rsync(projectDir.resolve("src/python"), projectDir.resolve("src/commonMain/resources/src/cardinal_sdk"))

	projectDir.resolve("src/commonMain/resources/src/cardinal_sdk/lib/$nativeLibFolder").mkdirs()
	projectDir.resolve("src/commonMain/resources/src/cardinal_sdk/lib/__init__.py").createNewFile()
	projectDir.resolve("src/commonMain/resources/src/cardinal_sdk/lib/$nativeLibFolder/__init__.py").createNewFile()

	rsync(
		projectDir.resolve("build/bin/$nativeLibFolder/$nativeLibBaseFolder/$nativeLibFileName"),
		projectDir.resolve("src/commonMain/resources/src/cardinal_sdk/lib/$nativeLibFolder/cardinal-sdk.${nativeLibFileName.substringAfterLast('.')}")
	)

	val tomlFile = projectDir.resolve("src/commonMain/resources/pyproject.toml")
	val content = tomlFile.readText()
	val version = project(":cardinal-sdk").version.toString()

	tomlFile.writeText(
		Regex("version = \"([^\"]+)\"").replace(content) {
			"version = \"$version\""
		}
	)

	val python = pythonPath.get()

	val workDir = projectDir.resolve("src/commonMain/resources")

	ProcessBuilder(python, "-m", "venv", "venv")
		.directory(workDir)
		.inheritIO()
		.start()
		.waitFor().also {
			check(it == 0) { "venv exited with code $it" }
		}

	val venv = projectDir.resolve("src/commonMain/resources/venv").absolutePath

	ProcessBuilder("$venv/bin/pip", "install", "--upgrade", "build")
		.directory(workDir)
		.inheritIO()
		.start()
		.waitFor().also {
			check(it == 0) { "Install build exited with code $it" }
		}

	ProcessBuilder(
		"$venv/bin/python",
		"-m",
		"build",
		"--wheel",
		"-C--build-option=--plat-name=$platformNameBuildOption"
	)
		.directory(workDir)
		.inheritIO()
		.start()
		.waitFor().also {
			check(it == 0) { "build exited with code $it" }
		}
}

fun prepareReleaseDistributionArchive(
	nativeLibFolder: String,
	nativeLibFileName: String,
	platformNameBuildOption: String
) = prepareDistributionArchive(
	nativeLibBaseFolder = "releaseShared",
	nativeLibFolder = nativeLibFolder,
	nativeLibFileName = nativeLibFileName,
	platformNameBuildOption = platformNameBuildOption
)

fun prepareDebugDistributionArchive(
	nativeLibFolder: String,
	nativeLibFileName: String,
	platformNameBuildOption: String
) = prepareDistributionArchive(
	nativeLibBaseFolder = "debugShared",
	nativeLibFolder = nativeLibFolder,
	nativeLibFileName = nativeLibFileName,
	platformNameBuildOption = platformNameBuildOption
)

data class PyPlatform(
	val taskName: String,
	val nativeLibFolder: String,
	val nativeLibFileName: String,
	val platformNameBuildOption: String,
)

tasks.register("removeDistDir") {
	group = "build"

	doLast {
		removeDistDir()
	}
}

val pyPlatforms = listOf(
	PyPlatform("prepareMingwX64", "mingwX64", "cardinal_sdk_native_pylib.dll", "win_amd64"),
	PyPlatform("prepareLinuxX64", "linuxX64", "libcardinal_sdk_native_pylib.so", "manylinux_2_35_x86_64"),
	PyPlatform("prepareMacosArm64", "macosArm64", "libcardinal_sdk_native_pylib.dylib", "macosx_11_0_arm64"),
)

val platformTasks = pyPlatforms.map { p ->
	tasks.register("${p.taskName}DistributionArchive") {
		group = "publishing"
		doLast {
			prepareReleaseDistributionArchive(
				nativeLibFolder = p.nativeLibFolder,
				nativeLibFileName = p.nativeLibFileName,
				platformNameBuildOption = p.platformNameBuildOption,
			)
		}
	}
}

pyPlatforms.map { p ->
	tasks.register("${p.taskName}DebugArchive") {
		group = "publishing"
		doLast {
			prepareDebugDistributionArchive(
				nativeLibFolder = p.nativeLibFolder,
				nativeLibFileName = p.nativeLibFileName,
				platformNameBuildOption = p.platformNameBuildOption,
			)
		}
	}
}

platformTasks.zipWithNext { prev, next -> next.configure { mustRunAfter(prev) } }

tasks.register("prepareDistributionArchiveForAllPlatforms") {
	group = "publishing"
	dependsOn(platformTasks)
}


// TODO should become task type
tasks.register("updateAutoGenerated") {
	doLast {
		rootDir.resolve("cardinal-sdk/build/generated/ksp/jvm/jvmMain/resources/pykt").mergeInto(
			projectDir.resolve("src/commonMain/kotlin")
		)
		rootDir.resolve("cardinal-sdk/build/generated/ksp/jvm/jvmMain/resources/py/cardinal_sdk").mergeInto(
			projectDir.resolve("src/python")
		)
	}
}