name: Generate Typescript SDK
on:
    push:
        branches:
            - develop
env:
    JSON_OUTPUT_DIR: ./cardinal-sdk/build/generated/ksp/jvm/jvmMain/resources
    BUILDER_JAR_PATH: sdk-codegen-codeGenerator.jar
    REPO_PATH: cardinal-sdk

jobs:
    setup:
        runs-on: ubuntu-latest
        name: Setup environment
        env:
            SDK_CODEGEN_VERSION: 1.5.0
        steps:
            -   name: Check out code
                uses: actions/checkout@v4
                with:
                    submodules: 'recursive'
                    token: ${{secrets.GH_PERSONAL_ACCESS_TOKEN}}

            -   name: Set up JDK 21
                uses: actions/setup-java@v4
                with:
                    distribution: 'corretto'
                    java-version: |
                        21
                    cache: 'gradle'
            -   name: Get builder jar
                run: |
                    curl -v -u ${{ secrets.GH_USERNAME }}:${{ secrets.GH_PERSONAL_ACCESS_TOKEN }} -L -o ${{ env.BUILDER_JAR_PATH }} https://maven.pkg.github.com/icure/sdk-codegen/com/icure/multiplatform-codegen/${{ env.SDK_CODEGEN_VERSION }}/multiplatform-codegen-${{ env.SDK_CODEGEN_VERSION }}-runner.jar

    generate_typescript:
        needs: setup
        runs-on: ubuntu-latest
        name: Generate JSON representation
        steps:
            - name: Generate JSON representation
              run: |
                  ./gradlew :cardinal-sdk:kspKotlin

    delete_auto_generated_files:
        needs: generate_typescript
        runs-on: ubuntu-latest
        steps:
            - name: Delete auto-generated files
              run: |
                  ./gradlew :ts-wrapper:clearAutoGenerated
                  
    generate_typescript_sdk:
        needs: generate_typescript
        runs-on: ubuntu-latest
        name: Generate Typescript SDK
        steps:
            - name: Generate Typescript SDK
              run: |
                java -jar ${{ env.BUILDER_JAR_PATH }} generate --ts --sdk --input=${{ env.JSON_OUTPUT_DIR }}

    add_newly_generated_files:
        needs: [generate_typescript_sdk, delete_auto_generated_files]
        runs-on: ubuntu-latest
        name: Add newly generated files
        steps:
            - name: Add newly generated files
              run: |
                  ./gradlew :ts-wrapper:updateAutoGenerated
                  
    prepare:
        needs: add_newly_generated_files
        runs-on: ubuntu-latest
        name: Prepare for commit
        steps:
            - name: Check if it builds
              run: |
                  ./gradlew :ts-wrapper:prepareDistributionPackage
                  

    commit_and_push:
        needs: prepare
        runs-on: ubuntu-latest
        name: Commit and push changes
        steps:
            - name: Configure Git
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"

            - name: Commit changes
              run: |
                  git add ts-wrapper/src/main/resources/cardinal-sdk
                  git commit -m "chore: Update Typescript SDK on PR merge to develop" || echo "No changes to commit"

            - name: Push changes
              run: |
                  git push origin HEAD:${{ github.head_ref }}

    create_pr:
        needs: commit_and_push
        runs-on: ubuntu-latest
        name: Create PR for changes
        if: github.event.pull_request.merged == true
        steps:
            -   name: Generate branch name
                id: generate_branch_name
                run: |
                    echo "BRANCH_NAME=typescript-sdk-$(date +'%Y%m%d%H%M')-${{ github.sha }}" >> $GITHUB_ENV

            -   name: Generate base
                id: generate_base
                run: |
                    echo "BASE_BRANCH=develop" >> $GITHUB_ENV
            

            -   name: Check git diff | if diff -> create a PR
                run: |
                    cd ${{ env.REPO_PATH }}
                    git diff --exit-code || echo "::set-output name=changes_detected::true"
                id: check_diff

            -   name: Bot Details
                id: bot-details
                uses: raven-actions/bot-details@v1

            -   name: Create a Pull Request
                if: steps.check_diff.outputs.changes_detected == 'true'
                uses: peter-evans/create-pull-request@v7
                with:
                    token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
                    commit-message: "Updated Typescript SDK"
                    title: "Updated Typescript SDK"
                    branch: ${{ env.BRANCH_NAME }}
                    base: ${{ env.BASE_BRANCH }}
                    path: ${{ env.REPO_PATH }}
                    author: ${{ steps.bot-details.outputs.name-email }}
                    committer: ${{ steps.bot-details.outputs.name-email }}
                    team-reviewers: 'icure/dev'
                    labels: 'automation'
